import Head from "next/head";
import { useState } from "react";
import Exercises from "../components/Exercises";
import Exercise from "../components/Exercises";
import HeroBanner from "../components/HeroBanner";
import Navbar from "../components/Navbar";
import SearchExercises from "../components/SearchExercises";

export default function Home() {
  const [bodyPart, setBodyPart] = useState("all");
  const [exercises, setExercises] = useState([]);

  return (
    <div className="max-w-6xl mx-auto py-6 px-5 overflow-x-hidden border border-red-400">
      <Head>
        <title>Exercises Dictionary by Andiwardaya</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <HeroBanner />
        <SearchExercises
          setExercises={setExercises}
          bodyPart={bodyPart}
          setBodyPart={setBodyPart}
        />
        <Exercises
          setExercises={setExercises}
          bodyPart={bodyPart}
          exercises={exercises}
        />
      </main>
    </div>
  );
}
